### ISSUE TITLE
Make a Website Version

### ISSUE THREAD

**Issue by itz-shyam** [Python3-8/Paint-Maker-Pro#1]
u can clone my repo if u want ;)

**Comment by prawnydagrate** [comment]
Bro thanks for the activity on my repo with literally no views

**Comment by prawnydagrate** [comment]
U dont have to give me ur repo, I can make one with p5.js

**Comment by itz-shyam** [comment]
k @Python3-8

**Comment by itz-shyam** [comment]
imma close dis
